---
title: Self-assessment for lab 7
author: Abby Komiske
doc: pdf
---

<!--
2024-04-29: Transforming data is a critical step in the data science, but it really takes a keen eye to identify what needs to be done, and some creativity to figure out how to do it. I'm glad that the second pass in class helped you gain a better understanding of the process.
-->

## Assessment

In preparation for lab 7, we went over data preparation with normalization and tokenization, as well as the enrichment process with re-coding, generation, and integration. This part of the process comes after framing and preparing but before analyzing. For the ‘transform’ lab, we used the State of the Union Addresses to transform the dataset, which included making it reproducible, documenting the code, and describing the resulting data and data dictionary. I mainly watched this lab instead of typing the code along with the instructor because I was a little overwhelmed with the readings. I found the enrichment process from the textbook to be confusing, but the lab with the slideshow coding helped me understand its bigger picture a lot more. Additionally, I only consulted the professor for this lab.
